### ISSUE TITLE
You owe Vattic some money

### ISSUE THREAD

**Issue by BaccarWozat** [FaithfulTeam/Faithful#87]
You sold Faithful through the marketplace. It has textures belonging to Vattic who had no intention of selling them, instead making them free for all to use so long as he received credit.
And now he has come back from a long absence:
https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/resource-packs/resource-pack-discussion/3132166-the-theft-of-faithful-32x32
And indicated he never gave you permission to hijack the project for your own personal financial gain.
You have the opportunity to do the right thing here and offer him some of the money. Not all of it-- after all, some of the textures in your current version of F32 belong to you-- but at least some sort of peace offering will smooth things in the community and help everyone move forward.
Or you can keep the money and be branded a thief.

**Comment by MaxBr5** [comment]
Refund the customers. Stop making money and credit Vattic or be a theif and someone to loathe. I'm saying it to you Vizzy.

**Comment by Cloud7050** [comment]
Associated Reddit thread by original creator Vattic: "The Theft of Faithful 32x32" @ https://www.reddit.com/r/Minecraft/comments/riv4tf/the_theft_of_faithful_32x32/

Some related coverage worth watching for context:

- [The Unfortunate Truth of Minecraft's #1 Texture Pack, by AntVenom](https://www.youtube.com/watch?v=kgZYBTlwaVs)
- [Why Does This Texture Pack Cost $8???, by ibxtoycat](https://www.youtube.com/watch?v=bHhD2Fyc1hc)

It is truly unfortunate what has transpired. Evidence was forged, lies were told & people were wronged. The community deserves to know.

**Comment by ghost** [comment]
🤡

**Comment by SkyNinja** [comment]
Unfortunately, the money is probably gone. Dude lives in Russia, IIRC, which is known to not care too much about international copyright law. His whole presence and ability to profit further will probably be wiped clean, though, so that's good.

I wonder if they filed DMCA complaints against this repository and the FaithfulTeam github page. Hope so.

Also, Carbonixx, it's not a surprise that you'd support this blatant theft, considering [the only repository](https://github.com/Carbonixx/aaaaaasdasdasd) [on your page](https://github.com/Gibbu/BetterDiscord-Themes). The fork button exists for a reason.

**Comment by Cloud7050** [comment]
Unfortunately, this does little to help your country's reputation in this time of crisis
